-- =====================================================
-- SEBITAM - TABELA DE MENSAGENS DO CHAT (REALTIME)
-- =====================================================
-- Execute este script no SQL Editor do Supabase
-- URL: https://supabase.com/dashboard/project/vwruogwdtbsareighmoc/sql

-- 1. Criar tabela de mensagens
CREATE TABLE IF NOT EXISTS mensagens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canal       TEXT NOT NULL,
    -- canal = 'sebitam-turma-1' | 'sebitam-turma-2' | ... | 'ibma'
    autor       TEXT NOT NULL,
    role        TEXT NOT NULL DEFAULT 'student',
    -- role = 'admin' | 'teacher' | 'student'
    texto       TEXT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 2. Desabilitar RLS para funcionamento com anon key
ALTER TABLE mensagens DISABLE ROW LEVEL SECURITY;

-- 3. Dar permissão total para anon e authenticated
GRANT ALL ON mensagens TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE mensagens_id_seq TO anon, authenticated;

-- 4. Índice para busca rápida por canal
CREATE INDEX IF NOT EXISTS idx_mensagens_canal ON mensagens(canal);
CREATE INDEX IF NOT EXISTS idx_mensagens_created_at ON mensagens(created_at DESC);

-- 5. HABILITAR REALTIME para a tabela mensagens
-- Isso permite que o Supabase envie eventos INSERT em tempo real
ALTER PUBLICATION supabase_realtime ADD TABLE mensagens;

-- 6. Verificar se foi criada corretamente
SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public'
AND table_name = 'mensagens'
ORDER BY ordinal_position;
