-- =====================================================
-- AMBIENTES: NOTIFICAÇÕES E MENSAGENS (SEBITAM + Escolas IBMA)
-- =====================================================
-- Execute no SQL Editor do Supabase
-- Separa dados por ambiente: 'sebitam' ou 'escolas-ibma'

-- 1. Tabela de Notificações
CREATE TABLE IF NOT EXISTS notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ambiente TEXT NOT NULL CHECK (ambiente IN ('sebitam', 'escolas-ibma')),
    destinatario_email TEXT,
    destinatario_tipo TEXT DEFAULT 'all',
    titulo TEXT NOT NULL,
    mensagem TEXT NOT NULL,
    tipo TEXT DEFAULT 'info' CHECK (tipo IN ('info', 'aviso', 'urgente', 'sucesso')),
    lida BOOLEAN DEFAULT false,
    link TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notificacoes_ambiente ON notificacoes(ambiente);
CREATE INDEX IF NOT EXISTS idx_notificacoes_email ON notificacoes(destinatario_email);
CREATE INDEX IF NOT EXISTS idx_notificacoes_lida ON notificacoes(lida);
CREATE INDEX IF NOT EXISTS idx_notificacoes_created ON notificacoes(created_at DESC);

-- 2. Tabela de Mensagens
CREATE TABLE IF NOT EXISTS mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ambiente TEXT NOT NULL CHECK (ambiente IN ('sebitam', 'escolas-ibma')),
    remetente_email TEXT NOT NULL,
    remetente_nome TEXT,
    destinatario_email TEXT NOT NULL,
    assunto TEXT,
    corpo TEXT NOT NULL,
    lida BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mensagens_ambiente ON mensagens(ambiente);
CREATE INDEX IF NOT EXISTS idx_mensagens_destinatario ON mensagens(destinatario_email);
CREATE INDEX IF NOT EXISTS idx_mensagens_remetente ON mensagens(remetente_email);

-- 3. Tabela de Tokens Push (para notificações mobile - opcional)
CREATE TABLE IF NOT EXISTS push_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ambiente TEXT NOT NULL CHECK (ambiente IN ('sebitam', 'escolas-ibma')),
    email TEXT NOT NULL,
    token TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(token)
);

CREATE INDEX IF NOT EXISTS idx_push_tokens_ambiente ON push_tokens(ambiente);
CREATE INDEX IF NOT EXISTS idx_push_tokens_email ON push_tokens(email);

-- Verificação
SELECT 'notificacoes' as tabela, COUNT(*) as colunas FROM information_schema.columns WHERE table_name = 'notificacoes'
UNION ALL
SELECT 'mensagens', COUNT(*) FROM information_schema.columns WHERE table_name = 'mensagens';
