-- =====================================================
-- CHAT EM GRUPO (estilo WhatsApp)
-- SEBITAM e Escolas IBMA separados por ambiente
-- =====================================================
-- Execute no SQL Editor do Supabase

-- 1. Grupos (salas de chat)
CREATE TABLE IF NOT EXISTS chat_grupos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ambiente TEXT NOT NULL CHECK (ambiente IN ('sebitam', 'escolas-ibma')),
    nome TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_grupos_ambiente ON chat_grupos(ambiente);

-- 2. Mensagens do grupo
CREATE TABLE IF NOT EXISTS chat_mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id BIGINT NOT NULL REFERENCES chat_grupos(id) ON DELETE CASCADE,
    remetente_email TEXT NOT NULL,
    remetente_nome TEXT NOT NULL,
    texto TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_mensagens_grupo ON chat_mensagens(grupo_id);
CREATE INDEX IF NOT EXISTS idx_chat_mensagens_created ON chat_mensagens(created_at DESC);

-- 3. Grupos padrão (um por ambiente) - executa apenas se não existir
INSERT INTO chat_grupos (ambiente, nome)
SELECT 'sebitam', 'Chat SEBITAM' WHERE NOT EXISTS (SELECT 1 FROM chat_grupos WHERE ambiente = 'sebitam');
INSERT INTO chat_grupos (ambiente, nome)
SELECT 'escolas-ibma', 'Chat Escolas IBMA' WHERE NOT EXISTS (SELECT 1 FROM chat_grupos WHERE ambiente = 'escolas-ibma');

-- 4. Habilitar Realtime (mensagens aparecem automaticamente para todos)
-- Execute: Supabase Dashboard > Database > Replication > enable "chat_mensagens"
-- OU execute:
ALTER PUBLICATION supabase_realtime ADD TABLE chat_mensagens;
